name: evidence-based-investigation
description: "Investigate problems using evidence-based analysis with session logs, error logs, and 5 Whys methodology. Use when debugging OpenClaw issues, analyzing system failures, tracing message delivery problems, or conducting root cause analysis that requires hard evidence from logs, files, or system state rather than assumptions."
version: 1.0.0
triggers:
  - investigate
  - debug
  - root cause
  - analyze failure
  - check logs
  - trace error
  - 5 whys
  - evidence-based
